/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TEST_PROG 0x31423456
#define TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define msg 1
extern  char ** msg_1(void *, CLIENT *);
extern  char ** msg_1_svc(void *, struct svc_req *);
extern int test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define msg 1
extern  char ** msg_1();
extern  char ** msg_1_svc();
extern int test_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
