/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"

struct arr *
add_1_svc(struct arrs *argp, struct svc_req *rqstp)
{
	static struct arr  result;
for(int i=0;i<10;i++){
		result.arr[i]= argp->arr1[i]+argp->arr2[i];
	}

	/*
	 * insert server code here
	 */

	return &result;
}
