/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sum.h"

bool_t
xdr_arr (XDR *xdrs, arr *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->arr;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->arr;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->arr, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arrs (XDR *xdrs, arrs *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 10  + 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr1, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr2, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->arr1;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register long *genp;

				for (i = 0, genp = objp->arr2;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 10  + 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr1, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->arr2, 10,
				sizeof (long), (xdrproc_t) xdr_long))
				 return FALSE;
		} else {
			{
				register long *genp;

				for (i = 0, genp = objp->arr1;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register long *genp;

				for (i = 0, genp = objp->arr2;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->arr1, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->arr2, 10,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}
